spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/env-media
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update
        default-schema: public

    show-sql: true

    generate-ddl: true

springdoc:
  api-docs:
    enabled: true
  path: /swagger-ui.html

