--CREATE TABLE IF NOT EXISTS movies {
--    id serial not null primary key,
--    created_date timestamp not null,
--    name varchar(50) not null,
--    rating double not null,
--    published_date timestamp not null,
--    thumbnail_id bigint not null,
--    genre_id bigint not null,
--    length bigint not null
--}